CREATE TABLE insurance_details (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    KIDSDRIV INTEGER,
    BIRTH DATETIME,
    AGE INTEGER,
    HOMEKIDS INTEGER,
    YOJ INTEGER,
    INCOME INTEGER,
    PARENT1 VARCHAR(100),
    HOME_VAL INTEGER,
    MSTATUS VARCHAR(100),
    GENDER VARCHAR(100),
    EDUCATION VARCHAR(100),
    OCCUPATION VARCHAR(100),
    TRAVTIME INTEGER,
    CAR_USE VARCHAR(100),
    BLUEBOOK INTEGER,
    TIF INTEGER,
    CAR_TYPE VARCHAR(100),
    RED_CAR VARCHAR(100),
    OLDCLAIM INTEGER,
    CLM_FREQ INTEGER,
    REVOKED VARCHAR(100),
    MVR_PTS INTEGER,
    CLM_AMT INTEGER,
    CAR_AGE INTEGER,
    CLAIM_FLAG INTEGER,
    URBANICITY VARCHAR(100),
    PRIMARY KEY (ID)
);

GO;

ALTER TABLE insurance_details AUTO_INCREMENT=10000000000;

GO;